export const pricingPlans = [
  {
    name: "Free",
    price: "$0",
    period: "/mo",
    badge: "Perfect for getting started",
    bullets: [
      "Track up to 10 items",
      "Basic reminders (1 lead time)",
      "Simple dashboard",
      "Email notifications",
    ],
    cta: "Get Started",
    highlight: false,
  },
  {
    name: "Pro",
    price: "$7",
    period: "/mo",
    badge: "Most Popular",
    subtext: "Billed $84/year",
    bullets: [
      "Unlimited items",
      "Multiple lead times",
      "Weekly digest emails",
      "Advanced filters & search",
      "Calendar export",
      "Priority email support",
    ],
    cta: "Upgrade to Pro",
    highlight: true,
  },
  {
    name: "Pro+",
    price: "$15",
    period: "/mo",
    badge: "Everything in Pro",
    subtext: "Billed $180/year",
    bullets: [
      "Smart suggestions",
      "Auto-import from email",
      "Team sharing (coming soon)",
      "API access",
      "Dedicated support",
    ],
    cta: "Go Pro+",
    highlight: false,
  },
];
